feat: Adicionar suporte para dark-mode
angolaosc/aosc.social pull request #51
Opened 2023-10-17 00:06 UTC by sombo20

# Team Debuguers

## Adicionou-se suporte para modo  dark com a biblioteca next-themes.

### Objectivo
Adiciona a funcionalidade de dark mode ao aplicativo, permitindo que os usuários alternem entre os modos claro e escuro. Isso melhora a experiência do usuário em ambientes com pouca luz e oferece mais opções de personalização.

Essa implementação, é para solucionar a issue #9 

@aosccode

2023-10-17 00:09 UTC, sombo20 commented
@antonio-pedro99 
Agora sim, consegui fazer o pull!

2023-10-18 07:27 UTC, Danguya commented on package.json
Recomendo que removas o react-icons e uses apenas o phosphor-react, pois lá já se encontram o mesmo ícones que prentens usar o **moon** e **sun**

https://phosphoricons.com/

2023-10-18 07:31 UTC, Danguya commented on src/app/components/footer/index.tsx
Em vez de usar o next-themes para gerenciar o Dark Mode, considero que podemos aproveitar o poder do Tailwind CSS para alternar entre os modos claro e escuro de forma mais integrada com nosso fluxo de trabalho atual. O Tailwind CSS possui um suporte excelente para isso e permite que você ajuste as cores de fundo e de texto diretamente em seu arquivo de configuração (geralmente tailwind.config.js), o que pode simplificar a personalização e a manutenção.

Além disso, ao adotar essa abordagem, podemos ter um controle mais granular sobre a estilização, garantindo que todas as cores e textos atendam aos requisitos de contraste, conforme mencionamos anteriormente.

Para fazer essa mudança, você pode revisitar as classes de cores do Tailwind CSS e personalizá-las de acordo com nossas necessidades específicas de contraste em ambos os modos. Consulte a documentação oficial do Tailwind CSS (https://tailwindcss.com/docs/dark-mode) para obter orientações sobre como configurar o Dark Mode usando o Tailwind CSS.

2023-10-18 07:33 UTC, Danguya requested changes
Obrigado por trabalhar no suporte ao Dark Mode.
É uma adição empolgante para o projeto! No entanto, ao revisar as alterações, observei alguns problemas de contraste que precisamos abordar para garantir a conformidade com as diretrizes WCAG AA e AAA.

Para manter a acessibilidade, é fundamental que as cores de fundo e de texto tenham um contraste adequado. Recomendo usar uma ferramenta de verificação de contraste, como a extensão "Color Picker" do navegador ou o site "WebAIM Color Contrast Checker" https://webaim.org/resources/contrastchecker, para avaliar e ajustar as cores usadas no Dark Mode.

Certifique-se de que todos os textos sejam claramente legíveis no modo escuro e que atendam aos requisitos de contraste. Isso é fundamental para garantir que os usuários com deficiências visuais possam usar o modo escuro com facilidade.

Uma vez que os problemas de contraste tenham sido abordados, ficarei feliz em revisar novamente o PR e, se tudo estiver em conformidade, aprová-lo para fusão.

2023-10-18 08:15 UTC, closed without merging