feat:  Adicionar suporte a multi-idioma
angolaosc/aosc.social pull request #63
Opened 2023-10-24 13:49 UTC by Afranioalves

## Team Debuguers
777-  Teve problemas de conflitos com a Pull Request passada, que resolvia a issue <b>feat: Adicionar suporte a novos idiomas</b> #8,  e acabou por ser fechada, quando ignorou-se os commit para resolver o confiltos.

Com isso criou-se essa nova Pull Request,  para resolver a issue #8

@aosccode

2023-10-24 13:52 UTC, Afranioalves commented
777- @antonio-pedro99  feito...

2023-10-25 00:35 UTC, sombo20 commented
@antonio-pedro99 
@Danguya

2023-10-25 06:48 UTC, trupakufi commented on src/app/components/header/mobile.tsx
> +      localStorage.setItem('i18nextLng', value)
Aqui não usaram a constante I18N_KEY porquê ?

2023-10-25 06:52 UTC, trupakufi commented on src/translate/i18n.ts
> +export { i18n }
Talvez seria mais suave estarem ao usar o t() apenas, do que o i18n.t(), parece muito mais conciso e fácil de se ler, era só exportar o t from i18n.

2023-10-25 06:53 UTC, trupakufi commented on src/translate/languages/en.ts
> +const messages = {
O nome mais usado para essa variável é "locales".

2023-10-25 06:54 UTC, trupakufi commented on src/translate/languages/index.ts
> +import { messages as portugueseMessages } from './pt'
De tal forma que aqui seria locales locales locales ao invés de messages.

2023-10-25 06:54 UTC, trupakufi commented on src/translate/languages/pt.ts
> +const messages = {
Aqui é o mesmo do que ali nas messages. Locales é melhor.

2023-10-25 06:56 UTC, trupakufi reviewed
E para finalizar, o i18n, podiam ter criado um hook, ou criado um state manager global para evitar imports do i18n por todo lado, ficaria responsabilidade do hook ou do state manager.

Mas gostei, estão de parabéns. 💯

2023-10-25 08:14 UTC, Afranioalves commented
> E para finalizar, o i18n, podiam ter criado um hook, ou criado um state manager global para evitar imports do i18n por todo lado, ficaria responsabilidade do hook ou do state manager.
> 
> Mas gostei, estão de parabéns. 💯

777- Mesmo se o state Manage global fosse criado,  ele deveria ser chamado em toda parte da aplicação  que precisasse ser traduzida, é semelhante ao Provider e o Context, importas o provider uma vez, mas chamas o context em toda parte que vai lhe utilizar.

Quanto mais legível o código estar melhor,  acredito que se estivesses para adicionar por exemplo Mandarim, farias bwe rápido até beber água seria difícil 😁😁

2023-10-25 08:19 UTC, trupakufi commented
> > E para finalizar, o i18n, podiam ter criado um hook, ou criado um state manager global para evitar imports do i18n por todo lado, ficaria responsabilidade do hook ou do state manager.
> > Mas gostei, estão de parabéns. 💯
> 
> 777- Mesmo se o state Manage global fosse criado, ele deveria ser chamado em toda parte da aplicação que precisasse ser traduzida, é semelhante ao Provider e o Context, importas o provider uma vez, mas chamas o context em toda parte que vai lhe utilizar.
> 
> Quanto mais legível o código estar melhor, acredito que se estivesses para adicionar por exemplo Mandarim, farias bwe rápido até beber água seria difícil 😁😁
> 
> Obrigado pelo feedback 🤝🤝

Sim, mas é diferente, porque o Context por exemplo é nativo e global, o i18n aí não é, é uma dependencia, imagina que um dia mudas de i18n para uma cena qualquer, vais ter que mudar em várias páginas e lugares, mas se usares um Contexto por exemplo, terias de mudar apenas no contexto que importa isso, e é sobre isso. Manutenção e pensar no futuro.

2023-10-25 08:21 UTC, Afranioalves commented on src/translate/i18n.ts
> +export { i18n }
777- 🤔🤔, t() !! Broh esse te pode ser qualquer coisa, quanto mais explicito código estiver melhor  para os outros dar sequência. 

Exemplo 

const sum =()=> para substituir por const s =()=>, quantas pessoas deveriam deduzir que o s é sum !!

O código deve estar explicito

2023-10-25 18:07 UTC, trupakufi commented on src/translate/i18n.ts
> +export { i18n }
Yep, t mesmo, é muito usado, é abreviação de translate, as pessoas que trabalham com internacionalização entendem isso.

2023-10-25 18:07 UTC, trupakufi approved these changes

2023-10-25 19:06 UTC, Danguya approved these changes
Parabens pela contrib. @Afranioalves

2023-10-25 19:27 UTC, antonio-pedro99 requested changes
Enquanto a PR ja foi contabilizada, vocês precisam resolver esses problemas.

2023-10-25 19:27 UTC, antonio-pedro99 commented on src/translate/languages/en.ts
> +                info: 'Take part now in the first face-to-face event of the Angola Open Source Commnunity in Luanda.',
```suggestion
                info: 'Be part of the first face-to-face event of the Angola Open Source Commnunity in Luanda.',
```

2023-10-25 19:27 UTC, antonio-pedro99 commented on src/translate/languages/en.ts
> +                title :`Creating a significant impact, on technological innovation in the country.`,
```suggestion
                title :`Creating a significant impact in the tech innovation in Angola.`,
```

2023-10-25 19:27 UTC, antonio-pedro99 commented on src/translate/languages/en.ts
> +                    title : 'Encouraging a free software culture.',
```suggestion
                    title : 'Encouraging the Free Software culture.',
```

2023-10-25 19:27 UTC, antonio-pedro99 commented on src/translate/languages/en.ts
> +                    description : 'Promote awareness of the benefits of open source software and encourage its use in Angola.'
Usar `Open-source` invés de `Open Source`

2023-10-25 19:27 UTC, antonio-pedro99 commented on src/translate/languages/en.ts
> +                    title : 'Accelerate open source development.',
Usar `Open-source` invés de `Open Source`

2023-10-25 19:27 UTC, antonio-pedro99 commented on src/translate/languages/en.ts
> +                    description : 'Offer resources and mentoring programs, workshops, and other events to help Angolan developers learn and contribute to excel in open source.'
```suggestion
                    description : 'Provide resources, mentorship programs, workshops, and other events to help Angolan developers learn and contribute and excel in open source.'
```

2023-10-25 19:27 UTC, antonio-pedro99 commented on src/translate/languages/en.ts
> +                    description:"It includes a week of online workshops and introductory training on Git and other essential tools for open source software development."
Usar `Open-source` invés de `Open Source`

2023-10-25 19:27 UTC, antonio-pedro99 commented on src/translate/languages/en.ts
> +                    description: "Open source software is a powerful tool for a country's technological and economic development."
Usar `Open-source` invés de `Open Source`

2023-10-25 19:27 UTC, antonio-pedro99 commented on src/translate/languages/en.ts
> +                    title: "Open Source code in Angola",
Usar `Open-source` invés de `Open Source`

2023-10-25 19:27 UTC, antonio-pedro99 commented on src/translate/languages/en.ts
> +                    description:"It connects experienced mentors, talented collaborators and free software organizations to contribute to open source projects."
Usar `Open-source` invés de `Open Source`
`Free Software` inves de `free software`

2023-10-25 19:27 UTC, antonio-pedro99 commented on src/translate/languages/en.ts
> +                    description:"It provides a solid base of knowledge and skills for Angolan developers who wish to contribute to free software projects."
`Free Software`

2023-10-25 19:27 UTC, antonio-pedro99 commented on src/translate/languages/en.ts
> +                    occupation:"FOUNDER | COMPUTER SCIENCE STUDENT",
pk captalizado?

2023-10-25 19:27 UTC, antonio-pedro99 commented on src/translate/languages/en.ts
> +                    description:"I'm a software developer and community leader. Passionate about sharing knowledge and enthusiastic about open source software."
Usar `Open-source` invés de `Open Source`

2023-10-25 19:27 UTC, antonio-pedro99 commented on src/translate/languages/en.ts
> +                    description : 'To strengthen the free software community in Angola by facilitating the exchange of knowledge, resources and experiences between developers.'
`Free Software`

2023-10-25 19:27 UTC, antonio-pedro99 commented on src/translate/languages/en.ts
> +                info: 'Take part now in the first face-to-face event of the Angola Open Source Commnunity in Luanda.',
Usar `Open-source` invés de `Open Source`

2023-10-25 21:50 UTC, trupakufi approved these changes

2023-10-31 10:54 UTC, antonio-pedro99 approved these changes
LGTM

2023-10-31 10:54 UTC, antonio-pedro99 commented on src/translate/languages/en.ts
> +                info: 'Be part of the first face-to-face event of the Angola Open-source Commnunity in Luanda.',
```suggestion
                info: 'Be part of the first in-person event of the Angola Open-source Commnunity in Luanda.',
```

2023-10-31 10:54 UTC, antonio-pedro99 commented on src/translate/languages/en.ts
> +                    description : 'Provide resources, mentorship programs, workshops, and other events to help Angolan developers learn and contribute and excel in open source.'
```suggestion
                    description : 'Provide resources, mentorship programs, workshops, and other events to help Angolan developers learn and contribute and excel in open-source.'
```

2023-10-31 10:54 UTC, antonio-pedro99 commented on src/translate/languages/en.ts
> +                    description : 'To strengthen the Free Software community in Angola by facilitating the exchange of knowledge, resources and experiences between developers.'
```suggestion
                    description : 'To strengthen the Free Software community in Angola by facilitating the exchange of knowledge, resources and experiences between developers and companies.'
```

2023-10-31 10:54 UTC, antonio-pedro99 commented on src/translate/languages/pt.ts
> +                    description : 'Oferecer recursos e programas de mentoria, workshops, e outros eventos para ajudar o desenvolvedor angolano aprender, e contribuir a se destacar no código aberto.'
```suggestion
                    description : 'Oferecer recursos e programas de mentoria, workshops, e outros eventos para ajudar o desenvolvedor angolano aprender, e contribuir a se destacar no movimento código aberto.'
```

2023-10-31 10:54 UTC, antonio-pedro99 commented on src/translate/languages/pt.ts
> +                    description:"Conecta mentores experientes, colaboradores talentosos e organizações de software livre para contribuir para projetos de open source."
```suggestion
                    description:"Conecta mentores experientes, colaboradores talentosos e organizações de software livre para contribuir para projetos de open-source."
```

2023-10-31 10:54 UTC, antonio-pedro99 commented on src/translate/languages/pt.ts
> +                    description:"Sou desenvolvedor de software e líder comunitário. Apaixonado por compartilhar conhecimento e entusiasta de softwares de código aberto."
```suggestion
                    description:"Sou desenvolvedor de software e líder comunitário. Apaixonado por compartilhar conhecimento e entusiasta de softwares de open-source"
```

2023-10-31 10:54 UTC, antonio-pedro99 commented on src/translate/languages/pt.ts
> +                    description: "O software de código aberto é uma ferramenta poderosa para o desenvolvimento tecnológico e econômico de um país."
```suggestion
                    description: "O software de open-source é uma ferramenta poderosa para o desenvolvimento tecnológico e econômico de um país."
```

2023-10-31 10:54 UTC, antonio-pedro99 commented on src/translate/languages/pt.ts
> +                    description : 'Promover a conscientização sobre os benefícios do software de código aberto e incentivar seu uso em Angola.'
```suggestion
                    description : 'Promover a conscientização sobre os benefícios do software open-source e incentivar seu uso em Angola.'
```

2023-10-31 10:54 UTC, antonio-pedro99 commented on src/translate/languages/pt.ts
> +                info: 'Participe agora do primeiro evento presencial da Angola Open Source Commnunity em Luanda.',
```suggestion
                info: 'Participe agora do primeiro evento presencial da Angola Open-source Commnunity em Luanda.',
```

2023-11-01 19:08 UTC, merged