Remove o header do AOSC Fest
angolaosc/aosc.social pull request #65
Opened 2023-12-14 22:24 UTC by sukuasoft

Neste PR removi o header do AOSC Fest, porque o evento já passou, assim como solicitado na issue [64](https://github.com/angolaosc/aosc.social/issues/64).

Alterações:
- [x] Removi a div que representa o header da AOSC Fest
- [x] Removi o padding que existia entre header principal e o header da AOSC Fest
- [x] Removi também dos arquivos de traduções os campos que correspondiam com o header da AOSC Fest.

2023-12-14 22:29 UTC, antonio-pedro99 requested changes
Olá @sukuasoft, valeu pela PR.

Além do meu comentário específico,  eu gostaria de informar que o menu já na está a funcionar conforme devia na plataforma mobile. 
Você podia dar uma olhada ou um testesinho?

2023-12-14 22:29 UTC, antonio-pedro99 commented on src/app/components/header/index.tsx
> +      className="dark:bg-bgd  w-full flex-col items-center justify-center px-6 hidden lg:flex fixed bg-white z-50"
Por quê removeu o top-10?

2023-12-14 23:01 UTC, sukuasoft commented on src/app/components/header/index.tsx
> +      className="dark:bg-bgd  w-full flex-col items-center justify-center px-6 hidden lg:flex fixed bg-white z-50"
Este top-10, adiciona um padding no topo do header. Servia para dar uma distancia entre header e a informação do AOSC  Fest que ficava por cima.
Mas como removi header do AOSC Fest não necessidade do top-10 ainda estar, porque senão ficará assim o header:
![bandicam 2023-12-14 23-51-51-205](https://github.com/angolaosc/aosc.social/assets/97813540/6bda80d2-b53a-4f32-aba9-64824bdd8eba)

2023-12-14 23:04 UTC, sukuasoft commented on src/app/components/header/index.tsx
> +      className="dark:bg-bgd  w-full flex-col items-center justify-center px-6 hidden lg:flex fixed bg-white z-50"
Sim, deu uma olhada no menu. Está do seguinte jeito: 
![bandicam 2023-12-14 23-56-26-679](https://github.com/angolaosc/aosc.social/assets/97813540/0cde2145-a094-4918-bab2-2d38320be95a)
![bandicam 2023-12-14 23-56-35-555](https://github.com/angolaosc/aosc.social/assets/97813540/edc51699-ed1e-469a-9184-ed1a908d4ecd)

2023-12-15 22:09 UTC, sukuasoft commented on src/app/components/header/index.tsx
> +      className="dark:bg-bgd  w-full flex-col items-center justify-center px-6 hidden lg:flex fixed bg-white z-50"
@antonio-pedro99 Por engano adicionei mais um commit, aqui. Era sobre a questão das métricas. Tem como fazer um rollback.

2023-12-19 11:00 UTC, antonio-pedro99 commented
@sukuasoft o building do vercel falhou, podes dar uma olhada?

2024-01-08 19:45 UTC, closed without merging