Update Headline Component Pictures
angolaosc/aosc.social pull request #91
Opened 2024-06-20 11:00 UTC by thiago-Coderr

In this pull request, I have updated the Headline component to display pictures of five contributors instead of just one. Previously, the component showcased only a single picture in a sequential order, which did not provide a good user interface experience. The new implementation ensures a more dynamic and inclusive presentation of contributors, enhancing the interface's overall visual appeal and usability
<img width="288" alt="Screenshot 2024-06-20 161518" src="https://github.com/angolaosc/aosc.social/assets/92113367/0294f450-2c85-4444-8e95-f921aa2ac442">
.

2024-06-20 11:14 UTC, antonio-pedro99 requested changes
Olá  @thiago-Coderr, obrigado pela PR.

Eu não acho que a gente quer usar dados estatísticos nessa headlines.
Essas fotos e número de membros da comunidade, devia vir do discord, Facebook, ou LinkedIn 

Dê uma olhada nessa issue #21

2024-06-20 11:31 UTC, thiago-Coderr commented
> Olá @thiago-Coderr, obrigado pela PR.
> 
> Eu não acho que a gente quer usar dados estatísticos nessa headlines. Essas fotos e número de membros da comunidade, devia vir do discord, Facebook, ou LinkedIn
> 
> Dê uma olhada nessa issue #21

A idea da minha pequena mudança no UI não foi dados estatisticos, mas sim eliminar a redundância nas imagens que são exatamente as mesma e de uma forma sequêncial, algo que da um look menos bom uma vez que o headline encontra-se no hero section, espero ter sido claro

2024-06-20 12:06 UTC, antonio-pedro99 commented
Eu entendo. Portanto, a gente prefere que resolvemos esse problema usando dados vindo do nosso servidor do discord, Facebook ou commudle.

2024-06-20 12:14 UTC, thiago-Coderr commented
> Eu entendo. Portanto, a gente prefere que resolvemos esse problema usando dados vindo do nosso servidor do discord, Facebook ou commudle.

Copied

2024-07-22 19:51 UTC, antonio-pedro99 commented
> > Eu entendo. Portanto, a gente prefere que resolvemos esse problema usando dados vindo do nosso servidor do discord, Facebook ou commudle.
> 
> Copied

@thiago-Coderr ainda com interesse em mexer nisso?

2025-03-24 21:33 UTC, antonio-pedro99 commented
No PR foi criado #99

2025-03-24 21:33 UTC, closed without merging